package thrift

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/bazelbuild/bazel-gazelle/config"
	"github.com/bazelbuild/bazel-gazelle/language"
	"github.com/bazelbuild/bazel-gazelle/rule"
)

func (_ *thriftLang) GenerateRules(args language.GenerateArgs) language.GenerateResult {
	tc := GetThriftConfig(args.Config)
	if tc.Mode == DisableMode {
		return language.GenerateResult{}
	}

	var regularThriftFiles []string
	for _, name := range args.RegularFiles {
		if strings.HasSuffix(name, ".thrift") {
			regularThriftFiles = append(regularThriftFiles, name)
		}
	}
	var genThriftFiles []string
	for _, name := range args.GenFiles {
		if strings.HasSuffix(name, ".thrift") {
			genThriftFiles = append(genThriftFiles, name)
		}
	}
	shouldSetVisibility := !hasDefaultVisibility(args.File)
	var res language.GenerateResult
	for _, file := range append(regularThriftFiles, genThriftFiles...) {
		fileInfo := thriftFileInfo(args.Dir, args.Rel, file)
		r := generateThrift(args.Rel, fileInfo, shouldSetVisibility)
		if r.IsEmpty(thriftKinds[r.Kind()]) {
			res.Empty = append(res.Empty, r)
		} else {
			res.Gen = append(res.Gen, r)
		}
	}
	sort.SliceStable(res.Gen, func(i, j int) bool {
		return res.Gen[i].Name() < res.Gen[j].Name()
	})
	res.Imports = make([]interface{}, len(res.Gen))
	for i, r := range res.Gen {
		res.Imports[i] = r.PrivateAttr(config.GazelleImportsKey)
	}
	res.Empty = append(res.Empty, generateEmpty(args.File, regularThriftFiles, genThriftFiles)...)
	return res
}

// RuleName returns a name for a thrift_library derived from the given strings.
// For each string, RuleName will look for a non-empty suffix of identifier
// characters and then append "_thrift" to that.
func RuleName(names ...string) string {
	base := "root"
	for _, name := range names {
		name = strings.Replace(name, "-", "_", -1)
		notIdent := func(c rune) bool {
			return !('A' <= c && c <= 'Z' ||
				'a' <= c && c <= 'z' ||
				'0' <= c && c <= '9' ||
				c == '_')
		}
		if i := strings.LastIndexFunc(name, notIdent); i >= 0 {
			name = name[i+1:]
		}
		if name != "" {
			base = name
			break
		}
	}
	return base + "_thrift"
}

// generateThrift creates a new thrift_library rule for a package. The rule may
// be empty if there are no sources.
func generateThrift(rel string, file FileInfo, shouldSetVisibility bool) *rule.Rule {
	name := RuleName(strings.TrimSuffix(file.Name, filepath.Ext(file.Name)))
	r := rule.NewRule("thrift_library", name)

	r.SetAttr("src", file.Name)
	r.SetPrivateAttr(config.GazelleImportsKey, file.Includes)
	r.SetPrivateAttr(FileInfoKey, file)
	if shouldSetVisibility {
		vis := checkInternalVisibility(rel, "//visibility:public")
		r.SetAttr("visibility", []string{vis})
	}
	return r
}

// generateEmpty generates a list of thrift_library rules that may be deleted.
// This is generated from existing thrift_library rules with src lists that
// don't match any static or generated files.
func generateEmpty(f *rule.File, regularFiles, genFiles []string) []*rule.Rule {
	if f == nil {
		return nil
	}
	knownFiles := make(map[string]bool)
	for _, f := range regularFiles {
		knownFiles[f] = true
	}
	for _, f := range genFiles {
		knownFiles[f] = true
	}
	var empty []*rule.Rule
outer:
	for _, r := range f.Rules {
		if r.Kind() != "thrift_library" {
			continue
		}
		srcs := r.AttrString("src")
		if len(srcs) == 0 && r.Attr("src") != nil {
			continue
		}
		if knownFiles[r.AttrString("src")] {
			continue outer
		}
		empty = append(empty, rule.NewRule("thrift_library", r.Name()))
	}
	return empty
}

// hasDefaultVisibility returns whether oldFile contains a "package" rule with
// a "default_visibility" attribute. Rules generated by Gazelle should not
// have their own visibility attributes if this is the case.
func hasDefaultVisibility(f *rule.File) bool {
	if f == nil {
		return false
	}
	for _, r := range f.Rules {
		if r.Kind() == "package" && r.Attr("default_visibility") != nil {
			return true
		}
	}
	return false
}

// checkInternalVisibility overrides the given visibility if the package is
// internal.
func checkInternalVisibility(rel, visibility string) string {
	if i := strings.LastIndex(rel, "/internal/"); i >= 0 {
		visibility = fmt.Sprintf("//%s:__subpackages__", rel[:i])
	} else if strings.HasPrefix(rel, "internal/") {
		visibility = "//:__subpackages__"
	}
	return visibility
}
